import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import newrelic from 'newrelic';
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const browserTimingHeader = newrelic.getBrowserTimingHeader({
    hasToRemoveScriptWrapper: true,
  });
  return (
    <html lang="en">
    <Head>
      <script
          type="text/javascript"
          dangerouslySetInnerHTML={{ __html: browserTimingHeader }}
      />
    </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
